### ISSUE TITLE
Setting up Kanban

### ISSUE THREAD

**Issue by DevaWinner** [DevaWinner/special-meals#21]
Hello
Our project link is: https://github.com/DevaWinner/special-meals/projects/1

We have 2 people in our group. I and @tajulafreen.
@tajulafreen is Student A
@DevaWinner is Student B

Thank you.

**Comment by Strangeal** [comment]
Hi @DevaWinner and @tajulafreen, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

**You have submitted a project, that doesn't contain a link to your GitHub `project`, Kindly consider adding a link to your Github `project` in your issue summary/body.**



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by DevaWinner** [comment]
Thank you for the correction. We thought the instruction was to have the link as the issue description. so we inserted it in the title. It has been corrected.

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info ✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [ ] Kindly assign all cards to the team members as per this [requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md#:~:text=Each%20of%20the%20team%20members%20should%20assign%20themselves%20to%20the%20correct%20cards.%20Decide%20who%20will%20be%20the%20assignee%20for%20the%20cards%20marked%20as%20group%20tasks.%20All%20cards%20on%20your%20Kanban%20board%20should%20have%20assignees.). All cards should have assignees.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DevaWinner** [comment]
Thank you very much @gemmen29, we had an oversight on that. We have sorted that out. 
Thank you once again.

**Comment by zainsadaqat** [comment]
# Pull Request Approved ✅ 🎊 🎉 
## Hello @DevaWinner and @tajulafreen 👋 

### You guys are ready to start working on the project! There is nothing else to say other than it's time to merge it.

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 ☑️ 

<img src="https://media1.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
